### ISSUE TITLE
上拉加载问题

### ISSUE THREAD

**Issue by weiming6790264** [mint-ui/mint-loadmore#12]
当加载内容超出屏幕可视区域，scroll会下移，拜托是什么原因

**Comment by Leopoldthecoder** [comment]
可以提供出问题的截图吗？不太理解“scroll 会下移”是什么意思。另外最好提供一下代码。

**Comment by weiming6790264** [comment]
我做的一个webapp中用到了mint-loadmore,地址是m.doufu.la/index/1,切换tab页时候，用上拉组件页面scroll会下移100px左右，未用的不会出现，调整好久都没发现问题，拜托了  
![](http://qn.zhangyongcun.com/b.png)
![](http://qn.zhangyongcun.com/a.png)

**Comment by Leopoldthecoder** [comment]
试试这样能否解决问题：首先把你项目的 recommend.vue 文件中 `ready` 钩子里 `this.getNovels();` 的注释去掉，然后在 `loadmore` 标签上添加 `:auto-fill="false"`。`auto-fill` 属性的作用见[文档](http://mint-ui.github.io/docs/#!/zh-cn/loadmore)。
