### ISSUE TITLE
上拉刷新-android

### ISSUE THREAD

**Issue by yyjazsf** [mint-ui/mint-loadmore#13]
vue v1.0.26
android: 4.4.2 lenovoK920 
loadmore 里面放一个mint的 swipe  和一个ul列表
android 和 chrome模拟 模式下都不能上拉刷新，
ios能用，但是不是很好用

下拉刷新可以用

**Comment by Leopoldthecoder** [comment]
请提供在线 demo 或代码

**Comment by yyjazsf** [comment]
经过测试 v-el:wrapper 外面不能包div，
v-el:wrapper 加上overflow:aoto 没问题了
第二点应该提示下，还是看源码知道的，否则 getScrollEventTarget 就是 window
