### ISSUE TITLE
不能正常滑动

### ISSUE THREAD

**Issue by yuluhuang** [mint-ui/mint-loadmore#15]
example中 在小步滑动的时候会反弹，this.getScrollTop(this.scrollEventTarget) 始终为 0，导致每次都会触发下拉事件

**Comment by Leopoldthecoder** [comment]
没太理解你的意思，我这边 example 在小步滑动时是正常的。能否给出动图？

**Comment by yuluhuang** [comment]
![Uploading 9月-08-2016 19-32-12.gif…](), 谷歌浏览器

**Comment by yuluhuang** [comment]
![http://7mj4lf.com1.z0.glb.clouddn.com/9%E6%9C%88-08-2016%2019-32-12.gif](http://7mj4lf.com1.z0.glb.clouddn.com/9%E6%9C%88-08-2016%2019-32-12.gif)
传个图片搞半天，谷歌浏览器，我不知道是不是个别原因

**Comment by Leopoldthecoder** [comment]
是[这个](http://leopoldthecoder.github.io/Demos/vue-loadmore/index.html)页面对吧？这个页面已经过时了，我把文档改一下。麻烦移步[这里](http://elemefe.github.io/mint-ui/#!/pull-down)看看能不能重现。
