### ISSUE TITLE
触摸滚动很不流畅，不知道哪里跟demo不一样

### ISSUE THREAD

**Issue by jiezhiyong** [mint-ui/mint-loadmore#17]

**Comment by Leopoldthecoder** [comment]
提供一下在线 demo

**Comment by jiezhiyong** [comment]
@Leopoldthecoder http://snow.kroom.me/vue/#!/page
手机上操作很不流畅，麻烦了

**Comment by Leopoldthecoder** [comment]
我手机上试了一下，感觉还行啊，很不流畅是指哪里？

**Comment by jiezhiyong** [comment]
@Leopoldthecoder 下拉刷新和上啦加载的动作是流畅的，不过内容区域滚动的时候跟您的Demo不一样，手指离开后立即停止了滚动。

**Comment by Leopoldthecoder** [comment]
试试这个：https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

**Comment by jiezhiyong** [comment]
@Leopoldthecoder thanks
