### ISSUE TITLE
动态加载数据后不能上拉

### ISSUE THREAD

**Issue by mowenjin** [mint-ui/mint-loadmore#19]
参照DEMO的示例，用FOR循环PUSH进去可以出现上拉效果，但是用AJAX请求回来的数据，PUSH进去之后，缺不能触发上拉效果？为什么呢？

**Comment by Leopoldthecoder** [comment]
请提供代码

**Comment by mowenjin** [comment]
已经解决，在loadmore上加标签:auto-fill="false"即可
