### ISSUE TITLE
_h is not defined

### ISSUE THREAD

**Issue by billwing** [mint-ui/mint-loadmore#20]
Has a error with SSR.
    
    ReferenceError: _h is not defined

**Comment by ghost** [comment]
我跟你同样的问题；报错如下
vue.common.js?9216:519[Vue warn]: Error when rendering component <mt-loadmore>: 
Uncaught ReferenceError: _h is not defined

有什么问题解决一下

**Comment by Leopoldthecoder** [comment]
降级 Vue 到 2.1.4 以下，或者使用最新版的 Mint

**Comment by ghost** [comment]
mint最新版本是2.0.6吧   vue版本也是2.1.0

**Comment by Leopoldthecoder** [comment]
是的，升到 Mint 2.0.6

**Comment by ghost** [comment]
还是同意的问题
vue.common.js?9216:519[Vue warn]: Error when rendering component :
Uncaught ReferenceError: _h is not defined

**Comment by niugm** [comment]
同样遇到此问题，求解，搞了半天，还以为自己代码哪里有问题
