### ISSUE TITLE
vue.common.js?6ef8:521 [Vue warn]: Error when rendering component <mt-loadmore>:

### ISSUE THREAD

**Issue by serrt** [mint-ui/mint-loadmore#22]
vue.common.js?6ef8:521 [Vue warn]: Error when rendering component <mt-loadmore>:

vue.common.js?6ef8:435 ReferenceError: _h is not defined(…)

**Comment by Leopoldthecoder** [comment]
降级 Vue 到 2.1.4 以下，或者使用最新版的 Mint
