### ISSUE TITLE
使用vue-webpack-boilerplate时应该如何去引入css文件?

### ISSUE THREAD

**Issue by funkyLover** [mint-ui/mint-loadmore#6]
我的项目使用的是[vue-webpack-boilerplate](https://github.com/vuejs-templates/webpack)
然后再引入css文件`require('mint-loadmore/lib/index.css');`的时候报错了
不管是在`<script>'还是`<style>`里面都不可以

**Comment by Leopoldthecoder** [comment]
抱歉，README 里写错了，应该是

``` javascript
require('mint-loadmore/lib/style.css');
```

**Comment by funkyLover** [comment]
这个问题解决了
但是我按照readme上的配置,却没有效果
渲染出来的DOM结构也有较大差异?
是还需要做什么额外配置吗?但是我又看到vue组件里面需要配置的项都已经有默认值了
捣乱了一会解决不了
我的项目中使用mint-loadmore
![2016-06-30 12 25 55](https://cloud.githubusercontent.com/assets/5418228/16476830/1d55cc36-3ebe-11e6-8ff7-766f71d78aef.png)
示例项目
![2016-06-30 12 26 31](https://cloud.githubusercontent.com/assets/5418228/16476833/23d95190-3ebe-11e6-84b7-d4207e4d4ced.png)

**Comment by Leopoldthecoder** [comment]
看上去是因为没有指定 `top-method` 和 `bottom-method`。不指定的话，对应方向上就不会有 DOM，也不会响应拉动释放。

**Comment by Leopoldthecoder** [comment]
可以看一下[文档](http://mint-ui.github.io/docs/#!/zh-cn/loadmore)

**Comment by funkyLover** [comment]
thx~
