### ISSUE TITLE
在IOS中发现一个BUG

### ISSUE THREAD

**Issue by nim888** [mint-ui/mint-loadmore#9]
ios 系统浏览器高度+反弹高度是不会等于 document.body.scrollHeight，在这个方法中checkBottomReached做了以下优化：

 document.body.scrollTop + document.documentElement.clientHeight   >=  document.body.scrollHeight :
this.$el.getBoundingClientRect().bottom <= this.scrollEventTarget.getBoundingClientRect().bottom

**Comment by Leopoldthecoder** [comment]
Fixed in https://github.com/ElemeFE/mint-ui/pull/148

**Comment by nightost** [comment]
好像部分页面会出现scrollHeight === scrollTop + innerHeight + 1的情况，不知道这是如何解释的
